# docker-compose.yml
redis:
    image: redis
    container_name: cache
    expose:
    - 6379
    
redispp:
    links:
    - redis
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    build: ./
    command:
    - /usr/src/redispp/launcher.sh